export interface Article {
  id?: string; // optional karena biasanya autogenerated
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  image_url?: string | null;
  author?: string;
  seo_title: string;
  seo_description: string;
  seo_keywords: string;
  canonical_url: string;
  meta_robots: string;
  created_at?: string; // jika ada timestamp di tabel
}
